### ISSUE TITLE
Host on github pages

### ISSUE THREAD

**Issue by adrianacorona** [caseywatts/kano-analysis#1]

**Comment by caseywatts** [comment]
Hosting on github successfully!
It's really annoying, I had to write overrides for c3js.

``` json
  "overrides": {
    "c3": {
      "main": [
        "c3.min.js",
        "c3.min.css"
      ]
    }
  },
```

Apparently its bower.json isn't quite right?

**Comment by caseywatts** [comment]
We're using `grunt build` to create a `dist` folder that's checked into github, then `git subtree push --prefix dist origin gh-pages` as specified on http://yeoman.io/learning/deployment.html to host it on github pages.

It's up here:
http://caseywatts.github.io/kano-analysis/
