### ISSUE TITLE
sample data into google sheets

### ISSUE THREAD

**Issue by adrianacorona** [caseywatts/kano-analysis#6]

**Comment by adrianacorona** [comment]
https://docs.google.com/spreadsheets/d/1THu-Vknk-UJX7UsDOjtsti_pDk6bnhyGS20Hjzxv46E/pubhtml?gid=0&single=true

**Comment by caseywatts** [comment]
Data now imports from Sheetsee!
Our sample public key currently hard-coded is 

> 1THu-Vknk-UJX7UsDOjtsti_pDk6bnhyGS20Hjzxv46E
